//! ABI-stable cdylib export for the ollama service backend.
//!
//! ollama is a BACKEND-ONLY plugin: its entire export is generated by the
//! toolkit's `export_service_plugin!`. The generic `service.*` tool surface
//! lives once in plugin-toolkit; this plugin only provides the backend.
//! `abi_stable` stays a direct dep because `#[export_root_module]` expands
//! to bare `::abi_stable` paths.
plugin_toolkit::export_service_plugin! {
    name: "ollama",
    target_compat: "any",
    backend: crate::OllamaBackend::new("ollama"),
}
